=head1 NAME

plenv-available - Show available perl5 versions from CPAN

=head1 SYNOPSIS

    % plenv available
    perl-5.17.8
    perl-5.16.2
    perl-5.14.3
    perl-5.12.5
    perl-5.10.1
    perl-5.8.9
    perl-5.6.2
    perl5.005_04
    perl5.004_05
    perl5.003_07

=head1 DESCRIPTION

This module shows available perl5 versions to install.

