=head1 NAME

plenv-global - Set or show the global Perl version

=head1 SYNOPSIS

    # Show the global Perl version
    % plenv global
    system

    # or Set the global perl version
    % plenv global 1.6.2

=head1 DESCRIPTION

Sets the global Perl version. You can override the global version at
any time by setting a directory-specific version with `plenv local'
or by setting the `PLENV_VERSION' environment variable.

<version> should be a string matching a Perl version known to plenv.
The special version string `system' will use your default system Perl.
Run `plenv versions' for a list of available Perl versions.
