=head1 NAME

plenv-help - Show help page

=head1 SYNOPSIS

    # Show plenv's main help page
    % plenv help

    # Show plenv's help document for 'install' sub command.
    % plenv help install

    # And show this page itself.
    % plenv help help

=head1 DESCRIPTION

This command shows help page for plenv.
