=head1 NAME

plenv-install - install Perl5 into ~/.plenv/

=head1 SYNOPSIS

    plenv install 5.16.2

    plenv install 5.16.2 -Dusethreads --as 5.16.2-threads

=head1 DESCRIPTION

This sub command install Perl binary into ~/.plenv/versions/.

=head1 OPTIONS

=over 4

=item -Dxxx

=item -Uxxx

=item -Axxx

Switches passed to perl Configure script.

ex. C<plenv install 5.10.1 -D usemymalloc -U uselargefiles>

=item --as

plenv applies alternative name to installation.

ex. C<plenv install 5.16.2 -Dusethreads --as 5.16.2-threads>

=item --build-dir=~/.plenv/build/

You can specify the directory to work building.

It is useful to save object files for debugging.

(Default: "build" in plenv directory)

=item --test

Run the test suite.

(Default: do not run test cases)

=item --force

Force install.

=back

=head1 INSTALLATION SOURCE

Current version of plenv supports following installation source.

=over 4

=item <version>

If you specify the version number, plenv fetches tar ball for the version from CPAN and install it.

=item /path/to/perl.tar.gz

When you specify the path to tar ball, plenv extract it and install.

=back

