=head1 NAME

plenv-local - Set or show the local application-specific Perl version

=head1 SYNOPSIS

    # Show the local application-specific Perl version
    % plenv local

    # Set the local application-specific Perl version

=head1 DESCRIPTION

Sets the local application-specific Perl version by writing the
version name to a file named `.perl-version'.

When you run a Perl command, plenv will look for a `.perl-version'
file in the current directory and each parent directory. If no such
file is found in the tree, plenv will use the global Perl version
specified with `plenv global'. A version specified with the
`PLENV_VERSION' environment variable takes precedence over local
and global versions.

<version> should be a string matching a Perl version known to plenv.
The special version string `system' will use your default system Perl.
Run `plenv versions' for a list of available Perl versions.

