=head1 NAME

plenv-rehash - rehash shims

=head1 SYNOPSIS

    % plenv rehash

=head1 DESCRIPTION

This subcommand regenerates ~/.plenv/shims/ directory.

You need to run this command after install CPAN module, installs command line script.

=head1 ARCHITECTURE

plenv puts shell script to ~/.plenv/shims/. It detect current perl5, and run the command under the current perl5.

