#!/usr/bin/env perl
use strict;
use warnings;
use Perl::Build;
use Getopt::Long;
use Pod::Usage;
use Getopt::Long;

my $test = undef;
GetOptions(
    'test' => \$test,
);

my $stuff   = shift @ARGV or pod2usage();
my $dest    = shift @ARGV or pod2usage();

my @configure_options = @ARGV ? @ARGV : ('-de');

if ($stuff =~ /\.(gz|bz2)$/) {
    Perl::Build->install_from_tarball(
        $stuff => (
            dst_path          => $dest,
            configure_options => \@configure_options,
            test              => $test,
        )
    );
} else {
    Perl::Build->install_from_cpan(
        $stuff => (
            dst_path          => $dest,
            configure_options => \@configure_options,
            test              => $test,
        )
    );
}

