#!/usr/bin/env bash
# Summary: List all Perl versions available to plenv
# Usage: plenv versions [--bare]
#
# Lists all Perl versions found in `$PLENV_ROOT/versions/*'.

set -e
[ -n "$PLENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(plenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(plenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && PLENV_VERSION=system plenv-which perl >/dev/null 2>&1; then
  print_version system
fi

for path in "${PLENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
