#!/usr/bin/env bash
# Usage: plenv version-file-read <file>
# Reads the first non-whitespace word from the specified version file,
# careful not to load it whole in case there's something crazy in it.
# Return 0 if a version is printed, 1 otherwise.
[ -e "$1" ] && \
  command -p awk \
    'BEGIN {rc=1} NF > 0 { print $1 ; exit rc=0 } END { exit rc }' "$1"
