#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: plenv which <command>
#
# Displays the full path to the executable that plenv will invoke when
# you run the given command.

set -e
[ -n "$PLENV_DEBUG" ] && set -x

# Provide plenv completions
if [ "$1" = "--complete" ]; then
  exec plenv shims --short
fi

expand_path() {
  if [ ! -d "$1" ]; then
    return 1
  fi

  local cwd="$PWD"
  cd "$1"
  pwd
  cd "$cwd"
}

remove_from_path() {
  local path_to_remove="$(expand_path "$1")"
  local result=""

  if [ -z "$path_to_remove" ]; then
    echo "${PATH}"
    return
  fi

  local paths
  IFS=: paths=($PATH)

  for path in "${paths[@]}"; do
    path="$(expand_path "$path" || true)"
    if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
      result="${result}${path}:"
    fi
  done

  echo "${result%:}"
}

PLENV_VERSION="$(plenv-version-name)"
PLENV_COMMAND="$1"

if [ -z "$PLENV_COMMAND" ]; then
  plenv-help --usage which >&2
  exit 1
fi

if [ "$PLENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${PLENV_ROOT}/shims")"
  PLENV_COMMAND_PATH="$(command -v "$PLENV_COMMAND" || true)"
else
  PLENV_COMMAND_PATH="${PLENV_ROOT}/versions/${PLENV_VERSION}/bin/${PLENV_COMMAND}"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`plenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$PLENV_COMMAND_PATH" ]; then
  echo "$PLENV_COMMAND_PATH"
else
  echo "plenv: $PLENV_COMMAND: command not found" >&2

  versions="$(plenv-whence "$PLENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Perl versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
