#!/usr/bin/env bash
# Usage: plenv version-file-read <file>
# Reads the first non-whitespace word from the specified version file,
# careful not to load it whole in case there's something crazy in it.
[ -e "$1" ] && \
  command -p awk 'NF > 0 { print $1 ; exit 0 } END { exit 1 }' "$1"
