#!/usr/bin/env bash
# Summary: Detect the file that sets the current plenv version
set -e
[ -n "$PLENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.perl-version" ]; then
      echo "${root}/.perl-version"
      exit
    elif [ -e "${root}/.plenv-version" ]; then
      echo "${root}/.plenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$PLENV_DIR"
[ "$PLENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${PLENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${PLENV_ROOT}/global" ]; then
  echo "${PLENV_ROOT}/global"
elif [ -e "${PLENV_ROOT}/default" ]; then
  echo "${PLENV_ROOT}/default"
else
  echo "$global_version_file"
fi
